using LiteObservableLanguages.Attributes;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Runtime.CompilerServices;
using System.Text;

namespace LiteObservableLanguages.SourceGenerator.Generators;

internal static class ModuleInitializerPolyfill
{
    private const string ModuleInitializerMetadataName = "System.Runtime.CompilerServices.ModuleInitializerAttribute";
    private const string SourceHintName = "LiteObservableLanguages.ModuleInitializerAttribute.g.cs";
    private static readonly string DisableGenerationForMetadataName = typeof(DisableGenerationForAttribute).FullName!;
    private static readonly string ModuleInitializerTypeName = nameof(ModuleInitializerAttribute);

    private const string SourceContent =
        """
        // <auto-generated/>
        namespace System.Runtime.CompilerServices
        {
            [global::System.AttributeUsage(AttributeTargets.Method, Inherited = false)]
            internal sealed class ModuleInitializerAttribute : Attribute { }
        }
        """;

    internal static void EmitIfNeeded(SourceProductionContext context, Compilation compilation)
    {
        if (IsGenerationDisabled(compilation)) return;
        if (compilation.GetTypeByMetadataName(ModuleInitializerMetadataName) is not null) return;

        context.AddSource(SourceHintName, SourceText.From(SourceContent, Encoding.UTF8));
    }

    private static bool IsGenerationDisabled(Compilation compilation)
    {
        var disableAttribute = compilation.GetTypeByMetadataName(DisableGenerationForMetadataName);
        if (disableAttribute is null) return false;

        foreach (var attribute in compilation.Assembly.GetAttributes())
        {
            if (!SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, disableAttribute)) continue;

            foreach (var argument in attribute.ConstructorArguments)
            {
                if (argument.Kind != TypedConstantKind.Array) continue;

                foreach (var constant in argument.Values)
                {
                    if ((constant.Value as INamedTypeSymbol)?.MetadataName == ModuleInitializerTypeName)
                    {
                        return true;
                    }
                }
            }
        }

        return false;
    }
}
